### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by SebaSeba** [tilastokeskus/Matertis#1]
ZIP ladattu 30.12.2014, klo 22:00. (Projektiin tutustuminen aloitettu jo aiemmin.)
- JavaDocin ja luokkakaavion avulla oli helppo alkaa hahmottamaan pelin toiminnallisuutta, sillä JavaDoc on jo tässä vaiheessa hyvin kattava ja kirjoitettu selkeästi, hyvällä englanninkielellä. Myös luokkakaavio on selkeä. 
- Metodit ja muuttujat on kuvaavasti nimetty. Metodit eivät ole liian pitkiä. Luokat on hyvin jaettu omiiin pakkauksiin jotka ovat hyvin nimettyjä. 
- Perintää ja rajapintoja käytetty hyvin ja monipuolisesti.
- _AbstractGameHandler, AbstractScoreHandler ja ObservableGameHandler luokat voisivat ehkä olla luokkakaaviossa, näiden käytön hahmottaminen otti hetken aikaa._
- Koodin lukeminen ja ymmärtäminen oli itselleni hyvää oppimista ja kertausta esim. rajapintojen käytöstä.

Lisäys vielä: Koodi ja dokumentointi oli mielestäni sen verran laadukasta, että omat taitoni eivät riittäneet keksimään parannettavaa koodista.

**Comment by olavim** [comment]
> AbstractGameHandler, AbstractScoreHandler ja ObservableGameHandler luokat voisivat ehkä olla luokkakaaviossa, näiden käytön hahmottaminen otti hetken aikaa.

Tällä hetkellä ei-julkaistussa versiossa `ObservableGameHandler` poistui kokonaan kun laitoin `AbstractGameHandler` luokan perimään `Observable` luokan suoraan.

Päätin jättää `AbstractGameHandler` ja `AbstractScoreHandler` luokat pois luokkakaaviosta, sillä ne eivät ole oleellisia ohjelman toiminnan kannalta (ainakaan tällä hetkellä). Niiden olemassaolo liittyy täysin laajennettavuuteen, eikä niillä ole ainakaan vielä konkreettista tarkoitusta, kun molemmilla abstraktilla luokalla on vain yksi toteuttava luokka (`AbstractGameHandler` luokan toteuttaa `GameHandler`, ja `AbstractScoreHandler` luokan toteuttaa `ScoreHandler`).

Ohjelman mikään komponentti ei siis suoraan kutsu mainitsemiasi abstrakteja luokkia, joten jätin ne luokkakaaviosta pois.

---

Kiitos palautteesta!
