### ISSUE TITLE
Koodikatselmointi #2

### ISSUE THREAD

**Issue by minttu** [tilastokeskus/Matertis#2]
Ladattu commit 8d899d5d2731a6736df06d1795846deb8c6c5869.

---

Koodista ei suoranaisesti ole mitään kritisoitavaa, OOP perjaatteita noudatettu mainiosti, kaikki on siististi järjestetty paketteihin, nimet ovat järkeviä ja dokumentaatio kattavaa.

---

Ehdottaisin kuitenkin että siirtäisit "data"n pois koodista jonkinlaisiin konfiguraatiotiedostoihin. Tällä tarkoitan lähinnä eri vaikeustasoja ja tetromino muotoja. Samalla `TetrominoFactory`ssä ei olisi tarvetta hardcodettaa eri mahdollisuuksia.

---

`mvn compile exec:java` ei toiminut, joten jouduin käyttämään hirveän pitkää `mvn compile exec:java -Dexec.mainClass=com.github.tilastokeskus.matertis.Main` komentoa saadakseni käyntiin. Testit eivät kääntyneet (`mvn test`) joten en saanut jariakaan ulos.

---

Muuten aika jees.

**Comment by olavim** [comment]
En noista komentorivikomennoista tiedä mitään; teen kaiken netbeansista käsin. Täällä päin kaikki testit myös kääntyvät, mikä lienee selitys tällekin. Mutta kiitos kuitenkin palautteesta! Konfiguraatiotiedostot kuulostavat hyvältä idealta, ja saatan tämän tehdäkkin nyt kun annettiin vähän lisäaikaa.

**EDIT:** Lisäsin _exec-maven-plugin_ plugarin pom.xml:ään, niin kääntyi tuon `mvn compile exec:java` komennon kanssa. Testit meni läpi myös `mvn test` komennolla.
